% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function O_wit = new(Version),
    % 'README on WIT-tag formatting.txt'
    if nargin == 0 || isempty(Version) || Version == 7, % Default: latest known version
        O_wit = wit.io.wit('WITec Project', [ ...
            wit.io.wit('Version', int32(7)) ...
            wit.io.wit('SystemInformation', [wit.io.wit('LastApplicationSessionIDs', wit.io.wit()) wit.io.wit('ServiceID', '') wit.io.wit('LicenseID', '') wit.io.wit('SystemID', '') wit.io.wit('ApplicationVersions', wit.io.wit(['MATLAB ' version]))]) ...
            wit.io.wit('NextDataID', int32(1)) ...
            wit.io.wit('ShellExtensionInfo') ... % For thumbnail, add: wit.io.wit('ThumbnailPreviewBitmap', [wit.io.wit('SizeX', int32(128)) wit.io.wit('SizeY', int32(128)) wit.io.wit('BitsPerPixel', int32(24)) wit.io.wit('BitmapData', uint8(Data))]) % Data->Im (for reading): Im = permute(reshape(Data, [3 128 128]), [3 2 1]); Im = Im(:,:,end:-1:1); Im->Data (for writing): Data = ipermute(uint8(Im(:,:,end:-1:1)), [3 2 1]);
            wit.io.wit('Data', wit.io.wit('NumberOfData', int32(0))) ...
            wit.io.wit('Viewer', [wit.io.wit('ViewerClassName 0', 'TVProjectManagerForm') wit.io.wit('Viewer 0', [wit.io.wit('TVCustomForm') wit.io.wit('TVProjectManagerForm')]) wit.io.wit('NumberOfViewer', int32(1))]) ...
            ]);
        O_wit.Magic = 'WIT_PR06'; % Enforce the correct Magic string!
    elseif Version == 6,
        O_wit = wit.io.wit('WITec Project', [ ...
            wit.io.wit('Version', int32(6)) ...
            wit.io.wit('SystemInformation', [wit.io.wit('LastApplicationSessionIDs', wit.io.wit()) wit.io.wit('ServiceID', '') wit.io.wit('LicenseID', '') wit.io.wit('ApplicationVersions', wit.io.wit(['MATLAB ' version]))]) ...
            wit.io.wit('NextDataID', int32(1)) ...
            wit.io.wit('ShellExtensionInfo') ... % For thumbnail, add: wit.io.wit('ThumbnailPreviewBitmap', [wit.io.wit('SizeX', int32(128)) wit.io.wit('SizeY', int32(128)) wit.io.wit('BitsPerPixel', int32(24)) wit.io.wit('BitmapData', uint8(Data))]) % Data->Im (for reading): Im = permute(reshape(Data, [3 128 128]), [3 2 1]); Im = Im(:,:,end:-1:1); Im->Data (for writing): Data = ipermute(uint8(Im(:,:,end:-1:1)), [3 2 1]);
            wit.io.wit('Data', wit.io.wit('NumberOfData', int32(0))) ...
            wit.io.wit('Viewer', [wit.io.wit('ViewerClassName 0', 'TVProjectManagerForm') wit.io.wit('Viewer 0', [wit.io.wit('TVCustomForm') wit.io.wit('TVProjectManagerForm')]) wit.io.wit('NumberOfViewer', int32(1))]) ...
            ]);
        O_wit.Magic = 'WIT_PR06'; % Enforce the correct Magic string!
    elseif Version >= 0 && Version <= 5, % Legacy versions
        O_wit = wit.io.wit('WITec Project', [ ...
            wit.io.wit('Version', int32(Version)) ...
            wit.io.wit('SystemInformation', [wit.io.wit('LastApplicationSessionIDs', wit.io.wit()) wit.io.wit('ApplicationVersions', wit.io.wit(['MATLAB ' version]))]) ... % (NOT IN ALL LEGACY VERSIONS)
            wit.io.wit('NextDataID', int32(1)) ...
            wit.io.wit('ShellExtensionInfo') ... % (NOT IN ALL LEGACY VERSIONS) % For thumbnail, add: wit.io.wit('ThumbnailPreviewBitmap', [wit.io.wit('SizeX', int32(128)) wit.io.wit('SizeY', int32(128)) wit.io.wit('BitsPerPixel', int32(24)) wit.io.wit('BitmapData', uint8(Data))]) % Data->Im (for reading): Im = permute(reshape(Data, [3 128 128]), [3 2 1]); Im = Im(:,:,end:-1:1); Im->Data (for writing): Data = ipermute(uint8(Im(:,:,end:-1:1)), [3 2 1]);
            wit.io.wit('Data', wit.io.wit('NumberOfData', int32(0))) ...
            wit.io.wit('Viewer', [wit.io.wit('ViewerClassName 0', 'TVProjectManagerForm') wit.io.wit('Viewer 0', [wit.io.wit('TVCustomForm') wit.io.wit('TVProjectManagerForm')]) wit.io.wit('NumberOfViewer', int32(1))]) ...
            ]);
        O_wit.Magic = 'WIT_PRCT'; % Enforce the correct Magic string!
    else, error('Unimplemented Version (%d)!', Version); end
end
