% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function O_wit = new_TData(Version, Caption),
    if nargin < 2 || isempty(Version) || Version == 7,
        Tag_TData = wit.io.wit('TData', [ ...
            wit.io.wit('Version', int32(0)) ...
            wit.io.wit('ID', int32(1)) ... % To be updated later in wit.io.wip.append
            wit.io.wit('ImageIndex', int32(0)) ...
            wit.io.wit('Caption', Caption) ...
            wit.io.wit('MetaData', wit.io.wit.empty) ...
            wit.io.wit('HistoryList', [wit.io.wit('Number Of History Entries', int32(0)) wit.io.wit('Dates', uint32.empty) wit.io.wit('Histories', '') wit.io.wit('Types', int32.empty)]) ...
            ]);
    elseif Version >= 0 && Version <= 5 || Version == 6, % Legacy versions OR v6
        Tag_TData = wit.io.wit('TData', [ ...
            wit.io.wit('Version', int32(0)) ...
            wit.io.wit('ID', int32(1)) ... % To be updated later in wit.io.wip.append
            wit.io.wit('ImageIndex', int32(0)) ...
            wit.io.wit('Caption', Caption) ...
            wit.io.wit('HistoryList', [wit.io.wit('Number Of History Entries', int32(0)) wit.io.wit('Dates', uint32.empty) wit.io.wit('Histories', '') wit.io.wit('Types', int32.empty)]) ...
            ]);
    else, error('Unimplemented Version (%d)!', Version); end
    O_wit = Tag_TData;
end
