% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function O_wit = new(Version),
    % 'README on WIT-tag formatting.txt'
    if nargin == 0 || isempty(Version) || Version == 7, % Default: latest known version
        O_wit = WITio.class.wit('WITec Project', [ ...
            WITio.class.wit('Version', int32(7)) ...
            WITio.class.wit('SystemInformation', [WITio.class.wit('LastApplicationSessionIDs', WITio.class.wit()) WITio.class.wit('ServiceID', '') WITio.class.wit('LicenseID', '') WITio.class.wit('SystemID', '') WITio.class.wit('ApplicationVersions', WITio.class.wit(['MATLAB ' version]))]) ...
            WITio.class.wit('NextDataID', int32(1)) ...
            WITio.class.wit('ShellExtensionInfo') ... % For thumbnail, add: WITio.class.wit('ThumbnailPreviewBitmap', [WITio.class.wit('SizeX', int32(128)) WITio.class.wit('SizeY', int32(128)) WITio.class.wit('BitsPerPixel', int32(24)) WITio.class.wit('BitmapData', uint8(Data))]) % Data->Im (for reading): Im = permute(reshape(Data, [3 128 128]), [3 2 1]); Im = Im(:,:,end:-1:1); Im->Data (for writing): Data = ipermute(uint8(Im(:,:,end:-1:1)), [3 2 1]);
            WITio.class.wit('Data', WITio.class.wit('NumberOfData', int32(0))) ...
            WITio.class.wit('Viewer', [WITio.class.wit('ViewerClassName 0', 'TVProjectManagerForm') WITio.class.wit('Viewer 0', [WITio.class.wit('TVCustomForm') WITio.class.wit('TVProjectManagerForm')]) WITio.class.wit('NumberOfViewer', int32(1))]) ...
            ]);
        O_wit.Magic = 'WIT_PR06'; % Enforce the correct Magic string!
    elseif Version == 6,
        O_wit = WITio.class.wit('WITec Project', [ ...
            WITio.class.wit('Version', int32(6)) ...
            WITio.class.wit('SystemInformation', [WITio.class.wit('LastApplicationSessionIDs', WITio.class.wit()) WITio.class.wit('ServiceID', '') WITio.class.wit('LicenseID', '') WITio.class.wit('ApplicationVersions', WITio.class.wit(['MATLAB ' version]))]) ...
            WITio.class.wit('NextDataID', int32(1)) ...
            WITio.class.wit('ShellExtensionInfo') ... % For thumbnail, add: WITio.class.wit('ThumbnailPreviewBitmap', [WITio.class.wit('SizeX', int32(128)) WITio.class.wit('SizeY', int32(128)) WITio.class.wit('BitsPerPixel', int32(24)) WITio.class.wit('BitmapData', uint8(Data))]) % Data->Im (for reading): Im = permute(reshape(Data, [3 128 128]), [3 2 1]); Im = Im(:,:,end:-1:1); Im->Data (for writing): Data = ipermute(uint8(Im(:,:,end:-1:1)), [3 2 1]);
            WITio.class.wit('Data', WITio.class.wit('NumberOfData', int32(0))) ...
            WITio.class.wit('Viewer', [WITio.class.wit('ViewerClassName 0', 'TVProjectManagerForm') WITio.class.wit('Viewer 0', [WITio.class.wit('TVCustomForm') WITio.class.wit('TVProjectManagerForm')]) WITio.class.wit('NumberOfViewer', int32(1))]) ...
            ]);
        O_wit.Magic = 'WIT_PR06'; % Enforce the correct Magic string!
    elseif Version >= 0 && Version <= 5, % Legacy versions
        O_wit = WITio.class.wit('WITec Project', [ ...
            WITio.class.wit('Version', int32(Version)) ...
            WITio.class.wit('SystemInformation', [WITio.class.wit('LastApplicationSessionIDs', WITio.class.wit()) WITio.class.wit('ApplicationVersions', WITio.class.wit(['MATLAB ' version]))]) ... % (NOT IN ALL LEGACY VERSIONS)
            WITio.class.wit('NextDataID', int32(1)) ...
            WITio.class.wit('ShellExtensionInfo') ... % (NOT IN ALL LEGACY VERSIONS) % For thumbnail, add: WITio.class.wit('ThumbnailPreviewBitmap', [WITio.class.wit('SizeX', int32(128)) WITio.class.wit('SizeY', int32(128)) WITio.class.wit('BitsPerPixel', int32(24)) WITio.class.wit('BitmapData', uint8(Data))]) % Data->Im (for reading): Im = permute(reshape(Data, [3 128 128]), [3 2 1]); Im = Im(:,:,end:-1:1); Im->Data (for writing): Data = ipermute(uint8(Im(:,:,end:-1:1)), [3 2 1]);
            WITio.class.wit('Data', WITio.class.wit('NumberOfData', int32(0))) ...
            WITio.class.wit('Viewer', [WITio.class.wit('ViewerClassName 0', 'TVProjectManagerForm') WITio.class.wit('Viewer 0', [WITio.class.wit('TVCustomForm') WITio.class.wit('TVProjectManagerForm')]) WITio.class.wit('NumberOfViewer', int32(1))]) ...
            ]);
        O_wit.Magic = 'WIT_PRCT'; % Enforce the correct Magic string!
    else, error('Unimplemented Version (%d)!', Version); end
end
