% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function O_wit = new_TData(Version, Caption),
    if nargin < 2 || isempty(Version) || Version == 7,
        Tag_TData = WITio.class.wit('TData', [ ...
            WITio.class.wit('Version', int32(0)) ...
            WITio.class.wit('ID', int32(1)) ... % To be updated later in WITio.class.wip.append
            WITio.class.wit('ImageIndex', int32(0)) ...
            WITio.class.wit('Caption', Caption) ...
            WITio.class.wit('MetaData', WITio.class.wit.empty) ...
            WITio.class.wit('HistoryList', [WITio.class.wit('Number Of History Entries', int32(0)) WITio.class.wit('Dates', uint32.empty) WITio.class.wit('Histories', '') WITio.class.wit('Types', int32.empty)]) ...
            ]);
    elseif Version >= 0 && Version <= 5 || Version == 6, % Legacy versions OR v6
        Tag_TData = WITio.class.wit('TData', [ ...
            WITio.class.wit('Version', int32(0)) ...
            WITio.class.wit('ID', int32(1)) ... % To be updated later in WITio.class.wip.append
            WITio.class.wit('ImageIndex', int32(0)) ...
            WITio.class.wit('Caption', Caption) ...
            WITio.class.wit('HistoryList', [WITio.class.wit('Number Of History Entries', int32(0)) WITio.class.wit('Dates', uint32.empty) WITio.class.wit('Histories', '') WITio.class.wit('Types', int32.empty)]) ...
            ]);
    else, error('Unimplemented Version (%d)!', Version); end
    O_wit = Tag_TData;
end
