fig = uifigure;

fig.Name = 'Project Manager';
fig.NumberTitle = 'off';
fig.MenuBar = 'none';
fig.ToolBar = 'none';
fig.Units = 'pixels'; % 'normalized' NOT supported!
fig.Color = [1 1 1];
XYWH = get(0, 'ScreenSize');
fig.Position = XYWH([3:4 3:4]).*[0.075 0.1 0.225 0.8];

height_table = 60;

h = uihtml(fig);
h.Position = [0 height_table fig.Position(3) fig.Position(4)-height_table];

strs = {'<tr><td><img height="32" width="32" src="TDText.png"/></td><td>&nbsp;Global (Calibration Information)</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDBitmap.png"/></td><td>&nbsp;Exfoliated graphene (Gr) on SiO2/Si-substrate&lt;Video Image (Data)</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDGraph_0.png"/></td><td>&nbsp;Reduced&lt;Image Scan 1 (Data)</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDText.png"/></td><td>&nbsp;Reduced&lt;Image Scan 1 (Information)</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDImage.png"/></td><td>&nbsp;Flat areas&lt;Mask 1</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDImage.png"/></td><td>&nbsp;1-layer Gr&lt;Mask 2</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDImage.png"/></td><td>&nbsp;2-layer Gr&lt;Mask 3</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDImage.png"/></td><td>&nbsp;3-layer (ABA-stacked) Gr&lt;Mask 4</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDImage.png"/></td><td>&nbsp;3-layer (ABC-stacked) Gr&lt;Mask 5</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDImage.png"/></td><td>&nbsp;Si&lt;Mask 6</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDGraph_2.png"/></td><td>&nbsp;Average&lt;1-layer Gr&lt;Mask 2</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDGraph_2.png"/></td><td>&nbsp;Average&lt;2-layer Gr&lt;Mask 3</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDGraph_2.png"/></td><td>&nbsp;Average&lt;3-layer (ABA-stacked) Gr&lt;Mask 4</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDGraph_2.png"/></td><td>&nbsp;Average&lt;3-layer (ABC-stacked) Gr&lt;Mask 5</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDGraph_2.png"/></td><td>&nbsp;Average&lt;Si&lt;Mask 6</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDGraph_1.png"/></td><td>&nbsp;Cross Section&lt;Reduced&lt;Image Scan 1</td></tr>', ...
'<tr><td><img height="32" width="32" src="TDGraph_2.png"/></td><td>&nbsp;1-layer Gr&lt;Point Scan 1 (Data)</td></tr>'};

h.HTMLSource = 'uihtml_JList.html';
drawnow;

S = struct();
S.items = [strs strs];
S.selection = [];
S.selectionMode = 2; % 0 = SINGLE_SELECTION, 1 = SINGLE_INTERVAL_SELECTION, 2 = MULTIPLE_INTERVAL_SELECTION
S.allowScrollbarKeydownEvents = true;
S.allowMouseHoverHighlights = true;
h.Data = S;

h.DataChangedFcn = @(src,event) disp(h.Data);
