% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function format = DataTree_format_TDLinearTransformation(Version_or_obj)
    if nargin == 0, Version_or_obj = []; end
    
    % Each row: wit-tag name, isVisible, {write-parser; read-parser}
    subformat_TDLinearTransformation_v5_v6_v7 = ... % Excluding the Version-tag
    	{ ...
        'Version' false {@int32; @int32}; ...
        'ModelOrigin_D' true {@double; @double}; ...
        'WorldOrigin_D' true {@double; @double}; ...
        'Scale_D' true {@double; @double}; ...
        'ModelOrigin' true {@single; @single}; ...
        'WorldOrigin' true {@single; @single}; ...
        'Scale' true {@single; @single} ...
        };
    
    % Each row: wit-tag name, isVisible, {subformat}
    format_TDLinearTransformation_v5_v6_v7 = ...
        [wid.DataTree_format_TData(Version_or_obj); ...
        wid.DataTree_format_TDTransformation(Version_or_obj); ...
        {'TDLinearTransformation' true subformat_TDLinearTransformation_v5_v6_v7}];
    
    format = format_TDLinearTransformation_v5_v6_v7;
end
