% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function O_wit = new(Version)
    % 'README on WIT-tag formatting.txt'
    if nargin == 0 || isempty(Version) || Version == 7, % Default: latest version
        O_wit = wit('WITec Data', [ ...
            wit('Version', int32(7)) ...
            wit('SystemInformation', [wit('LastApplicationSessionIDs', wit())  wit('ServiceID', '') wit('LicenseID', '') wit('ApplicationVersions', wit(['MATLAB ' version]))]) ...
            wit('Data', wit('NumberOfData', int32(0))) ...
            ]);
        O_wit.Magic = 'WIT_DA06'; % Enforce the correct Magic string!
    elseif Version == 6,
        O_wit = wit('WITec Data', [ ...
            wit('Version', int32(6)) ...
            wit('SystemInformation', [wit('LastApplicationSessionIDs', wit())  wit('ServiceID', '') wit('LicenseID', '') wit('ApplicationVersions', wit(['MATLAB ' version]))]) ...
            wit('Data', wit('NumberOfData', int32(0))) ...
            ]);
        O_wit.Magic = 'WIT_DA06'; % Enforce the correct Magic string!
    elseif Version == 5,
        O_wit = wit('WITec Data', [ ...
            wit('Version', int32(5)) ...
            wit('SystemInformation', [wit('LastApplicationSessionIDs', wit()) wit('ApplicationVersions', wit(['MATLAB ' version]))]) ...
            wit('Data', wit('NumberOfData', int32(0))) ...
            ]);
        O_wit.Magic = 'WIT_DATA'; % Enforce the correct Magic string!
    else, error('Unimplemented Version (%d)!', Version); end
end
