% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function format = wid_Data_format_TDLinearTransformation(obj),
    % Each row: wit-tag name, {isVisible; write-parser; read-parser}
    subformat_TDLinearTransformation_v5 = ... % Excluding the Version-tag
        { ...
        'Version' {false; @int32; @int32}; ...
        'ModelOrigin_D', {true; @double; @double}; ...
        'WorldOrigin_D', {true; @double; @double}; ...
        'Scale_D', {true; @double; @double}; ...
        'ModelOrigin', {true; @single; @single}; ...
        'WorldOrigin', {true; @single; @single}; ...
        'Scale', {true; @single; @single} ...
        };
    
    % Each row: wit-tag name, {subformat}
    format_TDLinearTransformation_v5 = ...
        [obj.wid_Data_format_TData(); ...
        obj.wid_Data_format_TDTransformation(); ...
        {'TDLinearTransformation' subformat_TDLinearTransformation_v5}];
    
    format = format_TDLinearTransformation_v5;
end
