% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function format = DataTree_format_TDSpaceTransformation(Version_or_obj),
    if nargin == 0, Version_or_obj = []; end
    
    % Each row: wit-tag name, isVisible, {write-parser; read-parser}
    subformat_TDSpaceTransformation = ... % Excluding the Version-tag
        { ...
        'Version' false {@int32; @int32}; ...
        'ViewPort3D' true ...
        { ... % Sub-format
        'ModelOrigin' true {@double; @double}; ...
        'WorldOrigin' true {@double; @double}; ...
        'Scale' true {@double; @double}; ...
        'Rotation' true {@double; @double} ...
        }; ...
        'LineInformationValid' true {@logical; @logical}; ...
        'LineStart_D' true {@double; @double}; ... % (NOT IN ALL LEGACY VERSIONS)
        'LineStart' true {@single; @single}; ...
        'LineStop_D' true {@double; @double}; ... % (NOT IN ALL LEGACY VERSIONS)
        'LineStop' true {@single; @single}; ...
        'NumberOfLinePoints' true {@int32; @int32} ...
        };
    
    % Each row: wit-tag name, isVisible, {subformat}
    format_TDSpaceTransformation = ...
        [WITio.core.wid.DataTree_format_TData(Version_or_obj); ...
        WITio.core.wid.DataTree_format_TDTransformation(Version_or_obj); ...
        {'TDSpaceTransformation' true subformat_TDSpaceTransformation}];
    
    format = format_TDSpaceTransformation;
end
