% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function obj = new_Image(O_wit),
    if nargin == 0 || isempty(O_wit), O_wit = WITio.core.wid.new(); end % Create O_wit
    Version = WITio.core.wip.get_Root_Version(O_wit);
    
    Tag_DataClassName = WITio.core.wit('DataClassName 0', 'TDImage');
    Tag_Data = WITio.core.wit('Data 0');
    
    Tag_TData = WITio.core.wip.new_TData(Version, sprintf('New %s', Tag_DataClassName.Data));
    if nargin < 2 || isempty(Version) || Version == 7,
        Tag_TDImage = WITio.core.wit('TDImage', [ ...
            WITio.core.wit('Version', int32(1)) ...
            WITio.core.wit('SizeX', int32(0)) WITio.core.wit('SizeY', int32(0)) ...
            WITio.core.wit('PositionTransformationID', int32(0)) ...
            WITio.core.wit('SecondaryTransformationID', int32(0)) ...
            WITio.core.wit('ZInterpretationID', int32(0)) ...
            WITio.core.wit('ImageDataIsInverted', true) ...
            WITio.core.wit('ImageData', [WITio.core.wit('Dimension', int32(2)) WITio.core.wit('DataType', int32(10)) WITio.core.wit('Ranges', int32([0 0])) WITio.core.wit('Data', uint8.empty)]) ... % Empty cannot be opened in WITec Project 2.10.3.3
            WITio.core.wit('Average', []) WITio.core.wit('Deviation', []) WITio.core.wit('LineAverage', []) WITio.core.wit('LineSumSqr', []) WITio.core.wit('LineSum', []) WITio.core.wit('LineA', []) WITio.core.wit('LineB', []) WITio.core.wit('LineChanged', logical.empty) WITio.core.wit('LineValid', logical.empty) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDImage];
    elseif Version == 6,
        Tag_TDImage = WITio.core.wit('TDImage', [ ...
            WITio.core.wit('Version', int32(1)) ...
            WITio.core.wit('SizeX', int32(0)) WITio.core.wit('SizeY', int32(0)) ...
            WITio.core.wit('PositionTransformationID', int32(0)) ...
            WITio.core.wit('ZInterpretationID', int32(0)) ...
            WITio.core.wit('ImageDataIsInverted', true) ...
            WITio.core.wit('ImageData', [WITio.core.wit('Dimension', int32(2)) WITio.core.wit('DataType', int32(10)) WITio.core.wit('Ranges', int32([0 0])) WITio.core.wit('Data', uint8.empty)]) ... % Empty cannot be opened in WITec Project 2.10.3.3
            WITio.core.wit('Average', []) WITio.core.wit('Deviation', []) WITio.core.wit('LineAverage', []) WITio.core.wit('LineSumSqr', []) WITio.core.wit('LineSum', []) WITio.core.wit('LineA', []) WITio.core.wit('LineB', []) WITio.core.wit('LineChanged', logical.empty) WITio.core.wit('LineValid', logical.empty) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDImage];
    elseif Version >= 0 && Version <= 5, % Legacy versions
        Tag_TDImage = WITio.core.wit('TDImage', [ ...
            WITio.core.wit('Version', int32(0)) ...
            WITio.core.wit('SizeX', int32(0)) WITio.core.wit('SizeY', int32(0)) ...
            WITio.core.wit('PositionTransformationID', int32(0)) ...
            WITio.core.wit('ZInterpretationID', int32(0)) ...
            WITio.core.wit('ImageData', [WITio.core.wit('Dimension', int32(2)) WITio.core.wit('DataType', int32(10)) WITio.core.wit('Ranges', int32([0 0])) WITio.core.wit('Data', uint8.empty)]) ... % Empty cannot be opened in WITec Project 2.10.3.3
            WITio.core.wit('Average', []) WITio.core.wit('Deviation', []) WITio.core.wit('LineAverage', []) WITio.core.wit('LineSumSqr', []) WITio.core.wit('LineSum', []) WITio.core.wit('LineA', []) WITio.core.wit('LineB', []) WITio.core.wit('LineChanged', logical.empty) WITio.core.wit('LineValid', logical.empty) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDImage];
    else, error('Unimplemented Version (%d)!', Version); end
    
    % Append these to the given (or created) O_wit
    [~, Pair] = WITio.core.wip.append(O_wit, [Tag_DataClassName Tag_Data]);
    
    % Create new wid
    obj = WITio.core.wid(Pair);
end
