% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function obj = new_Bitmap(O_wit),
    if nargin == 0 || isempty(O_wit), O_wit = WITio.core.wid.new(); end % Create O_wit
    Version = WITio.core.wip.get_Root_Version(O_wit);
    
    Tag_DataClassName = WITio.core.wit('DataClassName 0', 'TDBitmap');
    Tag_Data = WITio.core.wit('Data 0');
    
    Tag_TData = WITio.core.wip.new_TData(Version, sprintf('New %s', Tag_DataClassName.Data));
    if isempty(Version) || Version == 7,
        Tag_TDBitmap = WITio.core.wit('TDBitmap', [ ...
            WITio.core.wit('Version', int32(1)) ...
            WITio.core.wit('SizeX', int32(0)) WITio.core.wit('SizeY', int32(0)) ...
            WITio.core.wit('SpaceTransformationID', int32(0)) ...
            WITio.core.wit('SecondaryTransformationID', int32(0)) ...
            WITio.core.wit('BitmapData', [WITio.core.wit('Dimension', int32(2)) WITio.core.wit('DataType', int32(10)) WITio.core.wit('Ranges', int32([0 0])) WITio.core.wit('Data', uint8.empty)]) ... % Empty cannot be opened in WITec Project 2.10.3.3
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDBitmap];
    elseif Version == 6,
        Tag_TDBitmap = WITio.core.wit('TDBitmap', [ ...
            WITio.core.wit('Version', int32(1)) ...
            WITio.core.wit('SizeX', int32(0)) WITio.core.wit('SizeY', int32(0)) ...
            WITio.core.wit('SpaceTransformationID', int32(0)) ...
            WITio.core.wit('BitmapData', [WITio.core.wit('Dimension', int32(2)) WITio.core.wit('DataType', int32(10)) WITio.core.wit('Ranges', int32([0 0])) WITio.core.wit('Data', uint8.empty)]) ... % Empty cannot be opened in WITec Project 2.10.3.3
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDBitmap];
    elseif Version >= 0 && Version <= 5, % Legacy versions
        Tag_TDStream = WITio.core.wit('TDStream', [ ...
            WITio.core.wit('Version', int32(0)) ...
            WITio.core.wit('StreamSize', int32(0)) ...
            WITio.core.wit('StreamData', uint8.empty) ... % Empty cannot be opened in WITec Project 2.10.3.3
            ]);
        Tag_TDBitmap = WITio.core.wit('TDBitmap', [ ...
            WITio.core.wit('Version', int32(0)) ...
            WITio.core.wit('SpaceTransformationID', int32(0)) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDStream Tag_TDBitmap];
    else, error('Unimplemented Version (%d)!', Version); end
    
    % Append these to the given (or created) O_wit
    [~, Pair] = WITio.core.wip.append(O_wit, [Tag_DataClassName Tag_Data]);
    
    % Create new wid
    obj = WITio.core.wid(Pair);
end
