% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function destroy_all_Viewers(obj),
    % Minimal reset for WITec Project 2.10.3.3 to show a project manager.
    Viewer = obj.Tree.regexp('^Viewer<', true);
    Tag1 = WITio.wit('ViewerClassName 0', 'TVProjectManagerForm');
    Tag2 = WITio.wit('Viewer 0');
    TVCustomForm = WITio.wit('TVCustomForm');
    % COMMENTED TO RESET TO MINIMAL DEFAULT PROJECT MANAGER
%     TVCustomForm.Data = ...
%         [WITio.wit('Version', int32(0)) ...
%         WITio.wit('ShowCommand', int32(1)) ...
%         WITio.wit('MinimumPositionX', int32(-1)) ...
%         WITio.wit('MinimumPositionY', int32(-1)) ...
%         WITio.wit('MaximumPositionX', int32(-1)) ...
%         WITio.wit('MaximumPositionY', int32(-1)) ...
%         WITio.wit('WindowLeft', int32(0)) ...
%         WITio.wit('WindowTop', int32(100)) ...
%         WITio.wit('WindowRight', int32(400)) ...
%         WITio.wit('WindowBottom', int32(900))];
    TVProjectManagerForm = WITio.wit('TVProjectManagerForm');
    % COMMENTED TO RESET TO MINIMAL DEFAULT PROJECT MANAGER
%     TVProjectManagerForm.Data = ...
%         [WITio.wit('Version', int32(0)) ...
%         WITio.wit('SortType', int32(1)) ...
%         WITio.wit('ShowCategoryToolBar', true) ...
%         WITio.wit('Image', WITio.wit('Show', int32(1))) ...
%         WITio.wit('Filter', WITio.wit('Show', int32(1))) ...
%         WITio.wit('Cross Section', WITio.wit('Show', int32(1))) ...
%         WITio.wit('Spectrum', WITio.wit('Show', int32(1))) ...
%         WITio.wit('Histogram', WITio.wit('Show', int32(1))) ...
%         WITio.wit('Cursor', WITio.wit('Show', int32(1))) ...
%         WITio.wit('Interpretation', WITio.wit('Show', int32(0))) ...
%         WITio.wit('Transformation', WITio.wit('Show', int32(0))) ...
%         WITio.wit('Cross Section Info', WITio.wit('Show', int32(1))) ...
%         WITio.wit('Look and Feel', WITio.wit('Show', int32(1))) ...
%         WITio.wit('Text', WITio.wit('Show', int32(1)))];
    Tag2.Data = [TVCustomForm TVProjectManagerForm];
    Tag3 = WITio.wit('NumberOfViewer', int32(1));
    Viewer.Data = [Tag1 Tag2 Tag3];
end
