% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function O_wit = new_TData(Version, Caption),
    if nargin < 2 || isempty(Version) || Version == 7,
        Tag_TData = WITio.wit('TData', [ ...
            WITio.wit('Version', int32(0)) ...
            WITio.wit('ID', int32(1)) ... % To be updated later in WITio.wip.append
            WITio.wit('ImageIndex', int32(0)) ...
            WITio.wit('Caption', Caption) ...
            WITio.wit('MetaData', WITio.wit.empty) ...
            WITio.wit('HistoryList', [WITio.wit('Number Of History Entries', int32(0)) WITio.wit('Dates', uint32.empty) WITio.wit('Histories', '') WITio.wit('Types', int32.empty)]) ...
            ]);
    elseif Version >= 0 && Version <= 5 || Version == 6, % Legacy versions OR v6
        Tag_TData = WITio.wit('TData', [ ...
            WITio.wit('Version', int32(0)) ...
            WITio.wit('ID', int32(1)) ... % To be updated later in WITio.wip.append
            WITio.wit('ImageIndex', int32(0)) ...
            WITio.wit('Caption', Caption) ...
            WITio.wit('HistoryList', [WITio.wit('Number Of History Entries', int32(0)) WITio.wit('Dates', uint32.empty) WITio.wit('Histories', '') WITio.wit('Types', int32.empty)]) ...
            ]);
    else, error('Unimplemented Version (%d)!', Version); end
    O_wit = Tag_TData;
end
