% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function obj = new_Graph(O_wit),
    if nargin == 0 || isempty(O_wit), O_wit = wit.io.wid.new(); end % Create O_wit
    Version = wit.io.wip.get_Root_Version(O_wit);
    
    Tag_DataClassName = wit.io.wit('DataClassName 0', 'TDGraph');
    Tag_Data = wit.io.wit('Data 0');
    
    Tag_TData = wit.io.wip.new_TData(Version, sprintf('New %s', Tag_DataClassName.Data));
    if isempty(Version) || Version == 7,
        Tag_TDGraph = wit.io.wit('TDGraph', [ ...
            wit.io.wit('Version', int32(1)) ...
            wit.io.wit('SizeX', int32(1)) wit.io.wit('SizeY', int32(0)) wit.io.wit('SizeGraph', int32(0)) ...
            wit.io.wit('SpaceTransformationID', int32(0)) ...
            wit.io.wit('SecondaryTransformationID', int32(0)) ...
            wit.io.wit('XTransformationID', int32(0)) ...
            wit.io.wit('XInterpretationID', int32(0)) ...
            wit.io.wit('ZInterpretationID', int32(0)) ...
            wit.io.wit('DataFieldInverted', true) ...
            wit.io.wit('GraphData', [wit.io.wit('Dimension', int32(2)) wit.io.wit('DataType', int32(10)) wit.io.wit('Ranges', int32([1 0])) wit.io.wit('Data', uint8.empty)]) ...
            wit.io.wit('LineChanged', logical.empty) wit.io.wit('LineValid', logical.empty) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDGraph];
    elseif Version == 6,
        Tag_TDGraph = wit.io.wit('TDGraph', [ ...
            wit.io.wit('Version', int32(1)) ...
            wit.io.wit('SizeX', int32(1)) wit.io.wit('SizeY', int32(0)) wit.io.wit('SizeGraph', int32(0)) ...
            wit.io.wit('SpaceTransformationID', int32(0)) ...
            wit.io.wit('XTransformationID', int32(0)) ...
            wit.io.wit('XInterpretationID', int32(0)) ...
            wit.io.wit('ZInterpretationID', int32(0)) ...
            wit.io.wit('DataFieldInverted', true) ...
            wit.io.wit('GraphData', [wit.io.wit('Dimension', int32(2)) wit.io.wit('DataType', int32(10)) wit.io.wit('Ranges', int32([1 0])) wit.io.wit('Data', uint8.empty)]) ...
            wit.io.wit('LineChanged', logical.empty) wit.io.wit('LineValid', logical.empty) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDGraph];
    elseif Version >= 0 && Version <= 5, % Legacy versions
        Tag_TDGraph = wit.io.wit('TDGraph', [ ...
            wit.io.wit('Version', int32(0)) ...
            wit.io.wit('SizeX', int32(1)) wit.io.wit('SizeY', int32(0)) wit.io.wit('SizeGraph', int32(0)) ...
            wit.io.wit('SpaceTransformationID', int32(0)) ...
            wit.io.wit('XTransformationID', int32(0)) ...
            wit.io.wit('XInterpretationID', int32(0)) ...
            wit.io.wit('ZInterpretationID', int32(0)) ...
            wit.io.wit('GraphData', [wit.io.wit('Dimension', int32(2)) wit.io.wit('DataType', int32(10)) wit.io.wit('Ranges', int32([1 0])) wit.io.wit('Data', uint8.empty)]) ...
            wit.io.wit('LineChanged', logical.empty) wit.io.wit('LineValid', logical.empty) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDGraph];
    else, error('Unimplemented Version (%d)!', Version); end
    
    % Append these to the given (or created) O_wit
    [~, Pair] = wit.io.wip.append(O_wit, [Tag_DataClassName Tag_Data]);
    
    % Create new wid
    obj = wit.io.wid(Pair);
end
