% BSD 3-Clause License (LICENSE.txt)
% Copyright (c) 2019, Joonas T. Holmi (jtholmi@gmail.com)
% All rights reserved.

function obj = new_Graph(O_wit),
    if nargin == 0 || isempty(O_wit), O_wit = WITio.class.wid.new(); end % Create O_wit
    Version = WITio.class.wip.get_Root_Version(O_wit);
    
    Tag_DataClassName = WITio.class.wit('DataClassName 0', 'TDGraph');
    Tag_Data = WITio.class.wit('Data 0');
    
    Tag_TData = WITio.class.wip.new_TData(Version, sprintf('New %s', Tag_DataClassName.Data));
    if isempty(Version) || Version == 7,
        Tag_TDGraph = WITio.class.wit('TDGraph', [ ...
            WITio.class.wit('Version', int32(1)) ...
            WITio.class.wit('SizeX', int32(1)) WITio.class.wit('SizeY', int32(0)) WITio.class.wit('SizeGraph', int32(0)) ...
            WITio.class.wit('SpaceTransformationID', int32(0)) ...
            WITio.class.wit('SecondaryTransformationID', int32(0)) ...
            WITio.class.wit('XTransformationID', int32(0)) ...
            WITio.class.wit('XInterpretationID', int32(0)) ...
            WITio.class.wit('ZInterpretationID', int32(0)) ...
            WITio.class.wit('DataFieldInverted', true) ...
            WITio.class.wit('GraphData', [WITio.class.wit('Dimension', int32(2)) WITio.class.wit('DataType', int32(10)) WITio.class.wit('Ranges', int32([1 0])) WITio.class.wit('Data', uint8.empty)]) ...
            WITio.class.wit('LineChanged', logical.empty) WITio.class.wit('LineValid', logical.empty) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDGraph];
    elseif Version == 6,
        Tag_TDGraph = WITio.class.wit('TDGraph', [ ...
            WITio.class.wit('Version', int32(1)) ...
            WITio.class.wit('SizeX', int32(1)) WITio.class.wit('SizeY', int32(0)) WITio.class.wit('SizeGraph', int32(0)) ...
            WITio.class.wit('SpaceTransformationID', int32(0)) ...
            WITio.class.wit('XTransformationID', int32(0)) ...
            WITio.class.wit('XInterpretationID', int32(0)) ...
            WITio.class.wit('ZInterpretationID', int32(0)) ...
            WITio.class.wit('DataFieldInverted', true) ...
            WITio.class.wit('GraphData', [WITio.class.wit('Dimension', int32(2)) WITio.class.wit('DataType', int32(10)) WITio.class.wit('Ranges', int32([1 0])) WITio.class.wit('Data', uint8.empty)]) ...
            WITio.class.wit('LineChanged', logical.empty) WITio.class.wit('LineValid', logical.empty) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDGraph];
    elseif Version >= 0 && Version <= 5, % Legacy versions
        Tag_TDGraph = WITio.class.wit('TDGraph', [ ...
            WITio.class.wit('Version', int32(0)) ...
            WITio.class.wit('SizeX', int32(1)) WITio.class.wit('SizeY', int32(0)) WITio.class.wit('SizeGraph', int32(0)) ...
            WITio.class.wit('SpaceTransformationID', int32(0)) ...
            WITio.class.wit('XTransformationID', int32(0)) ...
            WITio.class.wit('XInterpretationID', int32(0)) ...
            WITio.class.wit('ZInterpretationID', int32(0)) ...
            WITio.class.wit('GraphData', [WITio.class.wit('Dimension', int32(2)) WITio.class.wit('DataType', int32(10)) WITio.class.wit('Ranges', int32([1 0])) WITio.class.wit('Data', uint8.empty)]) ...
            WITio.class.wit('LineChanged', logical.empty) WITio.class.wit('LineValid', logical.empty) ...
            ]);
        Tag_Data.Data = [Tag_TData Tag_TDGraph];
    else, error('Unimplemented Version (%d)!', Version); end
    
    % Append these to the given (or created) O_wit
    [~, Pair] = WITio.class.wip.append(O_wit, [Tag_DataClassName Tag_Data]);
    
    % Create new wid
    obj = WITio.class.wid(Pair);
end
